name: main
on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  build:
    - name: test
      runs-on: ubuntu-latest
      steps:
        - name: Version
          id: version
          run: echo ::set-output name=c::${GITHUB_REF#refs/tags/v}
        - uses: actions/checkout@v1
        - uses: borales/actions-yarn@v2.0.0
          with:
            cmd: install
        - uses: borales/actions-yarn@v2.0.0
          with:
            cmd: build
        - uses: borales/actions-yarn@v2.0.0
          with:
            auth-token: ${{ secrets.NPM_TOKEN }}
            cmd: publish --new-version ${{ steps.version.outputs.VERSION }}
        - name: push
          uses: github-actions-x/commit@v2.1
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            push-branch: 'master'
